dist: trusty
sudo: required

language: go
directories:
    - $HOME/.glide/cache
go:
  - 1.11.x

env:
  global:
  - ZOOKEEPER_PEERS=localhost:2181
  - KAFKA_PEERS=localhost:9092

addons:
  apt:
    packages:
      - gettext-base
      - libyaml-dev
      - openjdk-8-jre
      - python
      - python-dev
      - python-pip

services:
  - mysql

before_install:
  - pip install --user ccm
  - wget http://www.us.apache.org/dist/kafka/1.1.0/kafka_2.12-1.1.0.tgz -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
  - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"

install:
  - go get -u github.com/Masterminds/glide
  - go get -u golang.org/x/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - ccm create test -v 3.9 -n 1 -s

before_script:
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'uber'@'localhost' IDENTIFIED BY 'uber';"

script:
  - make cover_ci

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
