sudo: required

language: go

dist: trusty

go:
  - 1.11.1

matrix:
  include:
  - go: "1.11.1"
    services:
      - mysql
    env:
      - TEST_SUITE=unit
  - go: "1.11.1"
    env:
      - TEST_SUITE=integration
  - go: "1.11.1"
    env:
      - TEST_SUITE=xdc
      - ZOOKEEPER_PEERS=localhost:2181
      - KAFKA_PEERS=localhost:9092

addons:
  apt:
    packages:
      - gettext-base
      - libyaml-dev
      - openjdk-8-jre
      - python
      - python-dev
      - python-pip


before_install:
  - pip install --user ccm

install:
  - go get -u github.com/Masterminds/glide
  - go get -u golang.org/x/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - ccm create test -v 3.9 -n 1 -s
  - if [ "$TEST_SUITE" == "xdc" ]; then bash ./scripts/travis/install-xdc-deps.sh ; fi

before_script:
  - if [ "$TEST_SUITE" == "unit" ]; then bash ./scripts/travis/setup-mysql.sh ; fi

script:
  - if [ "$TEST_SUITE" == "unit" ]; then travis_wait 20 make cover_ci ; else echo 'skipping unit tests'; fi
  - if [ "$TEST_SUITE" == "integration" ]; then travis_wait 20 make cover_integration_ci ; else echo 'skipping integration tests'; fi
  - if [ "$TEST_SUITE" == "xdc" ]; then travis_wait 20 make cover_xdc_ci ; else echo 'skipping xdc tests'; fi

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
