
version: '3'
services:
  cockroach:
    hostname: cockroach
    image: cockroachdb/cockroach
    container_name: cockroach
    tty: false
    restart: "on-failure:5"
    security_opt:
     - "no-new-privileges"
    cap_drop:
    - ALL
    command: ["start", "--insecure"]

  temporal:
    image: temporalio/auto-setup:0.26.0
    ports:
     - "7233:7233"
    environment:
      - "DB=postgres"
      - "DB_PORT=26257"
      - "POSTGRES_USER=root"
      - "POSTGRES_PWD="
      - "POSTGRES_SEEDS=postgres"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cockroach
    links:
    - cockroach:postgres
    
  temporal-web:
    image: temporalio/web:0.25.0
    environment:
      - "TEMPORAL_GRPC_ENDPOINT=temporal:7233"
    ports:
      - "8088:8088"
    depends_on:
      - temporal
