version: '3'
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  elasticsearch:
    image: elasticsearch:6.8.8
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms100m -Xmx100m
  temporal:
    image: temporalio/auto-setup:${SERVER_TAG:-1.1.0}
    ports:
      - "7233:7233"
    volumes:
      - ${DYNAMIC_CONFIG_DIR:-../config/dynamicconfig}:/etc/temporal/config/dynamicconfig
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development_es.yaml"
      - "ENABLE_ES=true"
      - "ES_SEEDS=elasticsearch"
      - "KAFKA_SEEDS=kafka"
    depends_on:
      - cassandra
      - kafka
      - elasticsearch
  temporal-admin-tools:
    image: temporalio/admin-tools:${SERVER_TAG:-1.1.0}
    stdin_open: true
    tty: true
    environment:
      - "TEMPORAL_CLI_ADDRESS=temporal:7233"
    depends_on:
      - temporal
  temporal-web:
    image: temporalio/web:${WEB_TAG:-1.1.0}
    environment:
      - "TEMPORAL_GRPC_ENDPOINT=temporal:7233"
      - "TEMPORAL_PERMIT_WRITE_API=true"
    ports:
      - "8088:8088"
    depends_on:
      - temporal
