
version: '3'
services:
  cockroach:
    hostname: cockroach
    image: cockroachdb/cockroach
    container_name: cockroach
    tty: false
    restart: "on-failure:5"
    security_opt:
     - "no-new-privileges"
    cap_drop:
    - ALL
    command: ["start", "--insecure"]
  temporal:
    image: temporalio/server:${SERVER_TAG:-0.28.0}
    ports:
      - "7233:7233"
    volumes:
      - ../config:/mnt/temporal/config
    environment:
      - "AUTO_SETUP=true"
      - "DB=postgres"
      - "DB_PORT=26257"
      - "POSTGRES_USER=root"
      - "POSTGRES_PWD="
      - "POSTGRES_SEEDS=postgres"
      - "DYNAMIC_CONFIG_FILE_PATH=/mnt/temporal/config/dynamicconfig/development.yaml"
    depends_on:
      - cockroach
    links:
    - cockroach:postgres
  temporal-admin-tools:
    image: temporalio/admin-tools:${SERVER_TAG:-0.28.0}
    stdin_open: true
    tty: true
    environment:
      - "TEMPORAL_CLI_ADDRESS=temporal:7233"
    depends_on:
      - temporal
  temporal-web:
    image: temporalio/web:${WEB_TAG:-0.28.1}
    environment:
      - "TEMPORAL_GRPC_ENDPOINT=temporal:7233"
      - "TEMPORAL_PERMIT_WRITE_API=true"
    ports:
      - "8088:8088"
    depends_on:
      - temporal
