version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
  temporal:
    image: temporalio/auto-setup:${SERVER_TAG:-1.1.0}
    ports:
      - "7233:7233"
    volumes:
      - ${DYNAMIC_CONFIG_DIR:-../config/dynamicconfig}:/etc/temporal/config/dynamicconfig
    environment:
      - "DB=mysql"
      - "DB_PORT=3306"
      - "MYSQL_USER=root"
      - "MYSQL_PWD=root"
      - "MYSQL_SEEDS=mysql"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - mysql
  temporal-admin-tools:
    image: temporalio/admin-tools:${SERVER_TAG:-1.1.0}
    stdin_open: true
    tty: true
    environment:
      - "TEMPORAL_CLI_ADDRESS=temporal:7233"
    depends_on:
      - temporal
  temporal-web:
    image: temporalio/web:${WEB_TAG:-1.1.0}
    environment:
      - "TEMPORAL_GRPC_ENDPOINT=temporal:7233"
      - "TEMPORAL_PERMIT_WRITE_API=true"
    ports:
      - "8088:8088"
    depends_on:
      - temporal
