frontend.enableClientVersionCheck:
- value: true
  constraints: {}
history.persistenceMaxQPS:
- value: 3000
  constraints: {}
frontend.persistenceMaxQPS:
- value: 3000
  constraints: {}
frontend.historyMgrNumConns:
- value: 10
  constraints: {}
frontend.throttledLogRPS:
- value: 20
  constraints: {}
history.historyMgrNumConns:
- value: 50
  constraints: {}
history.defaultActivityRetryPolicy:
- value:
    InitialIntervalInSeconds: 1
    MaximumIntervalCoefficient: 100.0
    BackoffCoefficient: 2.0
    MaximumAttempts: 0
history.defaultWorkflowRetryPolicy:
- value:
    InitialIntervalInSeconds: 1
    MaximumIntervalCoefficient: 100.0
    BackoffCoefficient: 2.0
    MaximumAttempts: 0
system.advancedVisibilityWritingMode:
  - value: "on"
    constraints: {}
system.enableReadVisibilityFromES:
  - value: true
    constraints: {}
frontend.validSearchAttributes:
  - value:
      NamespaceId: "Keyword"
      WorkflowId: "Keyword"
      RunId: "Keyword"
      WorkflowType: "Keyword"
      StartTime: "Int"
      ExecutionTime: "Int"
      CloseTime: "Int"
      ExecutionStatus: "Int"
      HistoryLength: "Int"
      TaskQueue: "Keyword"
      KafkaKey: "Keyword"
      Encoding: "Keyword"
      CustomStringField: "String"
      CustomKeywordField: "Keyword"
      CustomIntField: "Int"
      CustomDoubleField: "Double"
      CustomBoolField: "Bool"
      CustomDatetimeField: "Datetime"
      TemporalChangeVersion: "Keyword"
      BinaryChecksums: "Keyword"
      CustomNamespace: "Keyword"
      Operator: "Keyword"
