frontend.enableClientVersionCheck:
- value: true
  constraints: {}
system.minRetentionDays:
- value: 0
  constraints: {}
history.persistenceMaxQPS:
- value: 3000
  constraints: {}
frontend.persistenceMaxQPS:
- value: 3000
  constraints: {}
frontend.historyMgrNumConns:
- value: 10
  constraints: {}
frontend.throttledLogRPS:
- value: 20
  constraints: {}
history.historyMgrNumConns:
- value: 50
  constraints: {}
system.advancedVisibilityWritingMode:
- value: "off"
  constraints: {}
history.defaultActivityRetryPolicy:
- value:
    InitialRetryIntervalInSeconds: 1
    MaximumRetryIntervalInSeconds: 120
    ExponentialBackoffCoefficient: 2.0
    MaximumAttempts: 0
