frontend.enableClientVersionCheck:
  - value: true
system.advancedVisibilityWritingMode:
  - value: "on"
system.enableReadVisibilityFromES:
  - value: true
frontend.validSearchAttributes:
  - value:
      NamespaceId: "Keyword"
      WorkflowId: "Keyword"
      RunId: "Keyword"
      WorkflowType: "Keyword"
      StartTime: "Int"
      ExecutionTime: "Int"
      CloseTime: "Int"
      ExecutionStatus: "Int"
      HistoryLength: "Int"
      TaskQueue: "Keyword"
      KafkaKey: "Keyword"
      Encoding: "Keyword"
      CustomStringField: "String"
      CustomKeywordField: "Keyword"
      CustomIntField: "Int"
      CustomDoubleField: "Double"
      CustomBoolField: "Bool"
      CustomDatetimeField: "Datetime"
      TemporalChangeVersion: "Keyword"
      BinaryChecksums: "Keyword"
      CustomNamespace: "Keyword"
      Operator: "Keyword"
      RolloutId: "Keyword"

