persistence:
  defaultStore: mysql-default
  visibilityStore: mysql-visibility
  numHistoryShards: 4
  datastores:
    mysql-default:
      sql:
        driverName: "mysql"
        databaseName: "cadence"
        connectAddr: "127.0.0.1:3306"
        connectProtocol: "tcp"
        user: "uber"
        password: "uber"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"
    mysql-visibility:
      sql:
        driverName: "mysql"
        databaseName: "cadence_visibility"
        connectAddr: "127.0.0.1:3306"
        connectProtocol: "tcp"
        user: "uber"
        password: "uber"
        maxConns: 2
        maxIdleConns: 2
        maxConnLifetime: "1h"

ringpop:
  name: cadence
  bootstrapMode: hosts
  bootstrapHosts: ["127.0.0.1:7933", "127.0.0.1:7934", "127.0.0.1:7935"]
  maxJoinDuration: 30s

services:
  frontend:
    rpc:
      port: 7933
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7936

  matching:
    rpc:
      port: 7935
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7938

  history:
    rpc:
      port: 7934
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7937

  worker:
    rpc:
      port: 7939
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7940

clustersInfo:
  enableGlobalDomain: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInitialFailoverVersion:
    active: 0
  clusterAddress:
    active:
      rpcName: "cadence-frontend"
      rpcAddress: "localhost:7933"

dcRedirectionPolicy:
  policy: "noop"
  toDC: ""

archival:
  enabled: false
  filestore:
    storeDirectory: "/tmp/development/blobstore/"
    defaultBucket: "cadence-development"
    customBuckets:
      - "custom-bucket-1"
      - "custom-bucket-2"

kafka:
  clusters:
    test:
      brokers:
        - 127.0.0.1:9092
  topics:
    cadence-visibility-dev:
      cluster: test
    cadence-visibility-dev-dlq:
      cluster: test
  applications:
    visibility:
      topic: cadence-visibility-dev
      dlq-topic: cadence-visibility-dev-dlq

elasticsearch:
  enable: false
  url:
    scheme: "http"
    host: "127.0.0.1:9200"
  indices:
    visibility: cadence-visibility-dev

publicClient:
  hostPort: "localhost:7933"
