persistence:
  defaultStore: mysql-default
  visibilityStore: mysql-visibility
  numHistoryShards: 4
  datastores:
    mysql-default:
      sql:
        pluginName: "mysql"
        databaseName: "cadence"
        connectAddr: "127.0.0.1:3306"
        connectProtocol: "tcp"
        user: "uber"
        password: "uber"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"
    mysql-visibility:
      sql:
        pluginName: "mysql"
        databaseName: "cadence_visibility"
        connectAddr: "127.0.0.1:3306"
        connectProtocol: "tcp"
        user: "uber"
        password: "uber"
        maxConns: 2
        maxIdleConns: 2
        maxConnLifetime: "1h"

ringpop:
  name: cadence
  bootstrapMode: hosts
  bootstrapHosts: ["127.0.0.1:7933", "127.0.0.1:7934", "127.0.0.1:7935"]
  maxJoinDuration: 30s

services:
  frontend:
    rpc:
      port: 7933
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7936

  matching:
    rpc:
      port: 7935
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7938

  history:
    rpc:
      port: 7934
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7937

  worker:
    rpc:
      port: 7939
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7940

clusterMetadata:
  enableGlobalDomain: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: "localhost:7933"

dcRedirectionPolicy:
  policy: "noop"
  toDC: ""

archival:
  history:
    status: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    status: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"

domainDefaults:
  archival:
    history:
      status: "enabled"
      URI: "file:///tmp/cadence_archival/development"
    visibility:
      status: "enabled"
      URI: "file:///tmp/cadence_vis_archival/development"

kafka:
  clusters:
    test:
      brokers:
        - 127.0.0.1:9092
  topics:
    cadence-visibility-dev:
      cluster: test
    cadence-visibility-dev-dlq:
      cluster: test

publicClient:
  hostPort: "localhost:7933"
