persistence:
  defaultStore: cass-default
  visibilityStore: cass-visibility
  numHistoryShards: 4
  datastores:
    cass-default:
      cassandra:
        hosts: "127.0.0.1"
        keyspace: "temporal_other"
    cass-visibility:
      cassandra:
        hosts: "127.0.0.1"
        keyspace: "temporal_visibility_other"

server:
  ringpop:
    name: temporal_other
    maxJoinDuration: 30s
  pprof:
    port: 9936

services:
  frontend:
    rpc:
      grpcPort: 9233
      membershipPort: 9933
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "temporal_other"

  matching:
    rpc:
      grpcPort: 9235
      membershipPort: 9935
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "temporal_other"

  history:
    rpc:
      grpcPort: 9234
      membershipPort: 9934
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "temporal_other"

  worker:
    rpc:
      grpcPort: 9240
      membershipPort: 9940
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "temporal_other"

clusterMetadata:
  enableGlobalDomain: true
  replicationConsumer:
    type: kafka
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "other"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "frontend"
      rpcAddress: "localhost:7933"
    standby:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "frontend"
      rpcAddress: "localhost:8933"
    other:
      enabled: true
      initialFailoverVersion: 2
      rpcName: "frontend"
      rpcAddress: "localhost:9933"

dcRedirectionPolicy:
  policy: "selected-apis-forwarding"
  toDC: ""

kafka:
  tls:
    enabled: false
    certFile: ""
    keyFile: ""
    caFile: ""
  clusters:
    test:
      brokers:
        - 127.0.0.1:9092
  topics:
    active:
      cluster: test
    active-dlq:
      cluster: test
    standby:
      cluster: test
    standby-dlq:
      cluster: test
    other:
      cluster: test
    other-dlq:
      cluster: test
  cadence-cluster-topics:
    active:
      topic: active
      dlq-topic: active-dlq
    standby:
      topic: standby
      dlq-topic: standby-dlq
    other:
      topic: other
      dlq-topic: other-dlq

archival:
  history:
    status: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    status: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"

domainDefaults:
  archival:
    history:
      status: "enabled"
      URI: "file:///tmp/temporal_archival/development"
    visibility:
      status: "enabled"
      URI: "file:///tmp/cadence_vis_archival/development"

publicClient:
  hostPort: "localhost:9933"
