# Adds CDC dependencies to main docker-compose files.
# Include platform specific file also:
# docker-compose -f docker-compose.yml -f docker-compose.linux.yml -f docker-compose.cdc.yml -f docker-compose.cdc.linux.yml up
version: "3.5"

services:
  temporal-ui-standby:
    image: temporalio/ui:2.11.2
    container_name: temporal-dev-ui-standby
    environment:
      - TEMPORAL_UI_PORT=8081
    security_opt:
      - no-new-privileges:true
    read_only: true

  temporal-ui-other:
    image: temporalio/ui:2.11.2
    container_name: temporal-dev-ui-other
    environment:
      - TEMPORAL_UI_PORT=8082
    security_opt:
      - no-new-privileges:true
    read_only: true
